Splitting peaks finder
spectre-team/native-algorithms pull request #39
Opened 2018-03-13 21:31 UTC by Sand3r-

The feature introduces a module for finding clear (aka splitting) peaks among the provided list of peaks, using user-supplied parameters and pre-calculated peak qualities.

Btw. sorry for FindClearPeaks being this long. Believe it or not, but I've spent ~3-4h on trying to make it smaller, and that's the furthest I could get it to.

2018-03-27 09:39 UTC, Daroslaw requested changes

2018-03-27 09:39 UTC, Daroslaw commented on src/Spectre.libGaussianMixtureModelling/ClearPeakFinder.cpp
> +    if (peaks.intensities.empty()) throw std::invalid_argument("Empty peak list");
Don't we have any custom Spectre-specific exceptions that would suit those cases?
Something like [this](https://github.com/spectre-team/native-algorithms/blob/40b1d0ace12967d94c25c9e40a2a45ff78b41da0/src/Spectre.libException/EmptyArgumentException.h#L28) for instance.

2018-03-27 09:39 UTC, Daroslaw commented on src/Spectre.libGaussianMixtureModelling/ClearPeakFinder.cpp
> +    if (peakQualities.empty()) throw std::invalid_argument("Empty peak quality list");
This function jollily assumes, that length of peak container is equal to length of quality container. Please consider adding a check for that with exception throw.

2018-03-31 19:19 UTC, Daroslaw submitted a review, later dismissed

2018-03-31 21:16 UTC, Daroslaw submitted a review, later dismissed

2018-04-10 11:19 UTC, Regis128 submitted a review, later dismissed

2018-04-14 11:42 UTC, Daroslaw approved these changes

2018-04-14 11:45 UTC, merged